import {
  AlertCircle,
  Boxes,
  CheckCircle2,
  ChevronDown,
  ChevronUp,
  ChevronsUpDown,
  Inbox,
  Info,
  LayoutDashboard,
  Loader2,
  Receipt,
  Server,
  ShoppingBag,
  Tags,
  TrendingDown,
  TrendingUp,
  Truck,
  Users,
  Wallet,
  X,
  XCircle,
  RefreshCw,
  type LucideIconData,
} from 'lucide-angular';

export const ICONS: Readonly<Record<string, LucideIconData>> = {
  'layout-dashboard': LayoutDashboard,
  tags: Tags,
  truck: Truck,
  boxes: Boxes,
  receipt: Receipt,
  'shopping-bag': ShoppingBag,
  wallet: Wallet,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  users: Users,
  server: Server,
  x: X,
  'chevron-up': ChevronUp,
  'chevron-down': ChevronDown,
  'chevrons-up-down': ChevronsUpDown,
  'check-circle': CheckCircle2,
  'x-circle': XCircle,
  'alert-circle': AlertCircle,
  info: Info,
  inbox: Inbox,
  'loader-2': Loader2,
  'refresh-cw': RefreshCw,
};

export function resolveIcon(name: string): LucideIconData | undefined {
  return ICONS[name];
}
