import {
  Activity,
  AlertCircle,
  Award,
  BarChart3,
  Boxes,
  Building2,
  Calendar,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  Coins,
  Crown,
  Database,
  Download,
  Eye,
  Filter,
  Globe,
  Inbox,
  Info,
  LayoutDashboard,
  Layers,
  Loader2,
  LogOut,
  Menu,
  Pencil,
  Plus,
  Power,
  Receipt,
  RefreshCw,
  Search,
  Server,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  Tags,
  Trash2,
  TrendingDown,
  TrendingUp,
  Truck,
  User,
  UserPlus,
  Users,
  Wallet,
  WifiOff,
  X,
  XCircle,
  Zap,
  type LucideIconData,
} from 'lucide-angular';

export const ICONS: Readonly<Record<string, LucideIconData>> = {
  'layout-dashboard': LayoutDashboard,
  coins: Coins,
  tags: Tags,
  truck: Truck,
  boxes: Boxes,
  receipt: Receipt,
  'shopping-bag': ShoppingBag,
  wallet: Wallet,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  users: Users,
  user: User,
  'user-plus': UserPlus,
  settings: Settings,
  server: Server,
  x: X,
  'chevron-up': ChevronUp,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevrons-up-down': ChevronsUpDown,
  'check-circle': CheckCircle2,
  'x-circle': XCircle,
  'alert-circle': AlertCircle,
  info: Info,
  inbox: Inbox,
  'loader-2': Loader2,
  'refresh-cw': RefreshCw,
  eye: Eye,
  search: Search,
  calendar: Calendar,
  filter: Filter,
  plus: Plus,
  pencil: Pencil,
  'trash-2': Trash2,
  power: Power,
  'log-out': LogOut,
  shield: Shield,
  'shield-check': ShieldCheck,
  'building-2': Building2,
  crown: Crown,
  layers: Layers,
  activity: Activity,
  'bar-chart-3': BarChart3,
  database: Database,
  sparkles: Sparkles,
  award: Award,
  globe: Globe,
  zap: Zap,
  download: Download,
  'wifi-off': WifiOff,
  menu: Menu,
};

export function resolveIcon(name: string): LucideIconData | undefined {
  return ICONS[name];
}
